---

- hosts: localhost
  connection: local
  become: True
  become_user: root
  roles:
    - role: "system-tools"
    - role: "install-docker"
    - role: "install-python3"
    - role: "build-essentials"
    - role: "paymo"
    - role: "terraform"
    - role: "terragrunt"
    - role: "terraform-docs"


