---

- name: Install the apt prop package
  apt: 
    name: software-properties-common
    state: present
    update_cache: yes

- name: "Install the python3 packages"
  apt:
    update_cache: yes
    pkg: "{{ packages }}"
    state: present

